import type { Certificate } from "@/types/content";

export const certificates: Certificate[] = [
  {
    type: "ai",
    rare: true,
    name: "Claude with Amazon Bedrock",
    logo: "anthropic",
    art: "BR",
    issuer: "Anthropic",
    date: "Sep 2026",
    move: "Claude on Bedrock",
    desc: "Prompts, tool use, RAG and agent workflows on AWS.",
  },
  {
    type: "ai",
    rare: true,
    name: "MCP: Advanced Topics",
    logo: "anthropic",
    art: "MCP+",
    issuer: "Anthropic",
    date: "Aug 2026",
    move: "Server Craft",
    desc: "Sampling, roots, notifications and HTTP transports.",
  },
  {
    type: "ops",
    name: "Docker Foundations Professional",
    logo: "docker",
    art: "DK",
    issuer: "Docker · LinkedIn",
    date: "Jul 2026",
    move: "Containerize",
    desc: "Images, Dockerfiles and Compose, from build to run.",
  },
  {
    type: "ai",
    name: "Career Essentials in Generative AI",
    logo: "microsoft",
    art: "GA",
    issuer: "Microsoft · LinkedIn",
    date: "Jul 2026",
    move: "Responsible AI",
    desc: "How generative AI works, and using it safely at work.",
  },
  {
    type: "be",
    name: "Backend Foundations Cohort 1.0",
    logo: "codersgyan",
    art: "BE",
    issuer: "Coder's Gyan",
    date: "Jun 2026",
    move: "Server Side",
    desc: "HTTP, databases, auth, system design and CI/CD.",
  },
  {
    type: "ai",
    name: "GenAI with JS",
    logo: "chaicode",
    art: "JS",
    issuer: "ChaiCode",
    date: "Nov 2025",
    move: "Agent Build",
    desc: "Agent orchestration: RAG, memory and MCP.",
  },
  {
    type: "be",
    name: "Complete Web Development Course",
    logo: "udemy",
    art: "WD",
    issuer: "Udemy",
    date: "Apr 2025",
    move: "Full Stack",
    desc: "JavaScript and Node through Next.js, SQL and Docker.",
  },
  {
    type: "be",
    name: "TalentNext Java Full Stack",
    logo: "wipro",
    art: "JV",
    issuer: "Wipro",
    date: "Oct 2024",
    move: "Java stack",
    desc: "Java full-stack development certification.",
  },
];
