import type { Certificate } from "@/types/content";

export const certificates: Certificate[] = [
  {
    type: "ai",
    rare: true,
    name: "Claude with Amazon Bedrock",
    art: "BR",
    issuer: "Anthropic Academy",
    date: "Sep 2026",
    move: "Bedrock",
    desc: "Calling Claude through AWS Bedrock.",
  },
  {
    type: "ai",
    rare: true,
    name: "MCP: Advanced Topics",
    art: "MCP+",
    issuer: "Anthropic",
    date: "Aug 2026",
    move: "Deep protocol",
    desc: "Advanced Model Context Protocol server patterns.",
  },
  {
    type: "ops",
    name: "Docker Foundations Professional",
    art: "DK",
    issuer: "LinkedIn Learning · Docker",
    date: "Jul 2026",
    hours: "3.7 HRS",
    move: "Containerize",
    desc: "Containerization and Docker products.",
  },
  {
    type: "ai",
    name: "Career Essentials in Generative AI",
    art: "GA",
    issuer: "Microsoft · LinkedIn",
    date: "Jul 2026",
    hours: "4.3 HRS",
    move: "Responsible AI",
    desc: "Generative AI, Copilot and responsible AI.",
  },
  {
    type: "be",
    name: "Backend Foundations Cohort 1.0",
    art: "BE",
    issuer: "Coder's Gyan",
    date: "Jun 2026",
    move: "Server side",
    desc: "Backend fundamentals cohort.",
  },
  {
    type: "be",
    name: "GenAI with JS",
    art: "JS",
    issuer: "ChaiCode",
    date: "Nov 2025",
    hours: "35+ HRS",
    move: "Full program",
    desc: "GenAI applications in JavaScript.",
  },
  {
    type: "be",
    name: "Complete Web Development Course",
    art: "WD",
    issuer: "Udemy",
    date: "Apr 2025",
    move: "Full stack",
    desc: "JavaScript and full-stack web development.",
  },
  {
    type: "be",
    name: "TalentNext Java Full Stack",
    art: "JV",
    issuer: "Wipro",
    date: "Oct 2024",
    move: "Java stack",
    desc: "Java full-stack development certification.",
  },
];
