import type { Certificate } from "@/types/content";

export const certificates: Certificate[] = [
  {
    type: "ai",
    rare: true,
    name: "Claude with Amazon Bedrock",
    art: "BR",
    issuer: "Anthropic Academy",
    date: "Sep 2026",
    move: "Bedrock",
    desc: "Calling Claude through AWS Bedrock.",
  },
  {
    type: "ai",
    rare: true,
    name: "MCP: Advanced Topics",
    art: "MCP+",
    issuer: "Anthropic",
    date: "Aug 2026",
    move: "Deep protocol",
    desc: "Advanced Model Context Protocol server patterns.",
  },
  {
    type: "ai",
    rare: true,
    name: "Claude Code in Action",
    art: "CC",
    issuer: "Anthropic",
    date: "Aug 2026",
    move: "Agentic coding",
    desc: "Working with Claude Code as a coding agent.",
  },
  {
    type: "ai",
    rare: true,
    name: "Introduction to MCP",
    art: "MCP",
    issuer: "Anthropic",
    date: "Jul 2026",
    move: "Tool use",
    desc: "Servers, tools, resources and prompts.",
  },
  {
    type: "ops",
    name: "Docker Foundations Professional",
    art: "DK",
    issuer: "LinkedIn Learning · Docker",
    date: "Jul 2026",
    hours: "3.7 HRS",
    move: "Containerize",
    desc: "Containerization and Docker products.",
  },
  {
    type: "ai",
    name: "Career Essentials in Generative AI",
    art: "GA",
    issuer: "Microsoft · LinkedIn",
    date: "Jul 2026",
    hours: "4.3 HRS",
    move: "Responsible AI",
    desc: "Generative AI, Copilot and responsible AI.",
  },
  {
    type: "be",
    name: "Backend Foundations Cohort 1.0",
    art: "BE",
    issuer: "Coder's Gyan",
    date: "Jun 2026",
    move: "Server side",
    desc: "Backend fundamentals cohort.",
  },
  {
    type: "be",
    name: "GenAI with JS",
    art: "JS",
    issuer: "ChaiCode",
    date: "Nov 2025",
    hours: "35+ HRS",
    move: "Full program",
    desc: "GenAI applications in JavaScript.",
  },
];
