import type { Project } from "@/types/content";
import { site } from "@/config/site";

const gh = (repo: string) => `https://github.com/raaaghavv/${repo}`;

export const projects: Project[] = [
  {
    name: "THIS SITE",
    art: "site",
    lines: ["THIS", "SITE"],
    colors: { bg: "cyan", title: "ink", shadow: "pink", band: "ink", bandText: "paper" },
    meta: "Oct 2026",
    tag: "A portfolio you ride through",
    category: "Interactive site",
    problem: "Developer portfolios all look like the same template.",
    built:
      "A skater drawn in SVG and posed by a hand-written 2D rig rides a scroll-driven course; every graphic is code.",
    result: { value: "99", unit: "Lighthouse on desktop, animated skater and all" },
    stack: ["Next.js", "TypeScript", "SVG"],
    live: site.url,
    repo: gh("raghavgoel.in"),
  },
  {
    name: "UPSTREAM",
    art: "upload",
    lines: ["UP", "STREAM"],
    colors: { bg: "pink", title: "ink", shadow: "acid", band: "ink", bandText: "paper" },
    meta: "Mar 2026",
    tag: "Resumable uploads & downloads",
    category: "File transfer",
    problem: "A dropped connection meant restarting a big transfer.",
    built: "tus chunked uploads and Service Worker downloads over HTTP Range, resumed from IndexedDB.",
    result: { value: "Refresh-proof", unit: "Uploads and downloads pick up where they stopped" },
    stack: ["tus", "Service Workers", "Express"],
    live: "https://up-stream.vercel.app",
    repo: gh("UpStream"),
  },
  {
    name: "POP LYRICS",
    art: "lyrics",
    lines: ["POP", "LYRICS"],
    colors: { bg: "ink", title: "acid", shadow: "pink", band: "paper", bandText: "ink", bolt: "paper" },
    meta: "Jun 2026",
    tag: "Floating synced lyrics",
    category: "Browser extension",
    problem: "Following the lyrics meant keeping the music tab open.",
    built: "A Chrome extension for Spotify and YouTube Music that floats synced lyrics in Document PiP.",
    result: { value: "Always on top", unit: "Lyrics synced to the track" },
    stack: ["Chrome MV3", "React", "Vite"],
    repo: gh("Pop-Lyrics"),
  },
  {
    name: "SYNTH",
    art: "stream",
    colors: { bg: "blue", title: "acid", shadow: "ink", band: "acid", bandText: "ink" },
    meta: "Feb 2026",
    tag: "Music & video streaming",
    category: "Media streaming",
    problem: "Whole media files had to load before they could play.",
    built: "Express streams audio and video as HTTP 206, into a hand-built player with sync and PiP.",
    result: { value: "Seek anywhere", unit: "Streamed over HTTP 206, no player library" },
    stack: ["Express", "MongoDB", "Next.js"],
    live: "https://synth-stream.vercel.app",
    repo: gh("synth"),
  },
  {
    name: "API WATCH",
    art: "monitor",
    lines: ["API", "WATCH"],
    colors: { bg: "white", title: "pink", shadow: "ink", band: "ink", bandText: "paper" },
    meta: "Jan 2026",
    tag: "Live API logs over SSE",
    category: "Developer tool",
    problem: "Watching API logs meant refreshing a page.",
    built: "An SSE server broadcasting to every client, and a useSSE hook that reconnects by itself.",
    result: { value: "Zero refreshes", unit: "Logs push live and reconnect on their own" },
    stack: ["Express", "SSE", "React"],
    live: "https://api-watch-kappa.vercel.app",
    repo: gh("API-Watch"),
  },
];
