import type { Project } from "@/types/content";

const gh = (repo: string) => `https://github.com/raaaghavv/${repo}`;

export const projects: Project[] = [
  {
    name: "UPSTREAM",
    art: "upload",
    lines: ["UP", "STREAM"],
    colors: { bg: "pink", title: "ink", shadow: "acid", band: "ink", bandText: "paper" },
    meta: "Mar 2026",
    tag: "Resumable uploads & downloads",
    category: "File transfer",
    problem: "A dropped connection meant restarting a big transfer.",
    built: "tus chunked uploads and Service Worker downloads over HTTP Range, resumed from IndexedDB.",
    result: { value: "tus + Range", unit: "Transfers survive a refresh" },
    stack: ["tus", "Service Workers", "Express"],
    live: "https://up-stream.vercel.app",
    repo: gh("UpStream"),
  },
  {
    name: "SYNTH",
    art: "stream",
    colors: { bg: "blue", title: "acid", shadow: "ink", band: "acid", bandText: "ink" },
    meta: "Feb 2026",
    tag: "Music & video streaming",
    category: "Media streaming",
    problem: "Whole media files had to load before they could play.",
    built: "Express streams audio and video as HTTP 206, into a hand-built player with sync and PiP.",
    result: { value: "HTTP 206", unit: "Streaming with no player library" },
    stack: ["Express", "MongoDB", "Next.js"],
    live: "https://synth-stream.vercel.app",
    repo: gh("synth"),
  },
  {
    name: "API WATCH",
    art: "monitor",
    lines: ["API", "WATCH"],
    colors: { bg: "white", title: "pink", shadow: "ink", band: "ink", bandText: "paper" },
    meta: "Jan 2026",
    tag: "Live API logs over SSE",
    category: "Developer tool",
    problem: "Watching API logs meant refreshing a page.",
    built: "An SSE server broadcasting to every client, and a useSSE hook that reconnects by itself.",
    result: { value: "SSE", unit: "Real-time and auto-reconnecting" },
    stack: ["Express", "SSE", "React"],
    live: "https://api-watch-kappa.vercel.app",
    repo: gh("API-Watch"),
  },
  {
    name: "POP LYRICS",
    art: "lyrics",
    lines: ["POP", "LYRICS"],
    colors: { bg: "ink", title: "acid", shadow: "pink", band: "paper", bandText: "ink", bolt: "paper" },
    meta: "Jun 2026",
    tag: "Floating synced lyrics",
    category: "Browser extension",
    problem: "Following the lyrics meant keeping the music tab open.",
    built: "A Chrome extension for Spotify and YouTube Music that floats synced lyrics in Document PiP.",
    result: { value: "Always on top", unit: "Lyrics synced to the track" },
    stack: ["Chrome MV3", "React", "Vite"],
    repo: gh("Pop-Lyrics"),
  },
  {
    name: "AI CLI",
    art: "terminal",
    colors: { bg: "acid", title: "ink", shadow: "pink", band: "ink", bandText: "acid" },
    meta: "Aug 2025",
    tag: "Agent that clones website UIs",
    category: "AI agent",
    problem: "Recreating a site's UI by hand is slow.",
    built: "A Gemini CLI agent: give it a URL and it clones the UI, assets and paths included.",
    result: { value: "URL → clone", unit: "A site's UI from one prompt" },
    stack: ["Gemini", "Agents", "Node.js"],
    demo: "https://youtu.be/ujkAfBUTYBc",
    repo: gh("AI-CLI"),
  },
  {
    name: "PERSONA AI",
    art: "masks",
    lines: ["PERSONA", "AI"],
    colors: { bg: "cyan", title: "ink", shadow: "pink", band: "ink", bandText: "paper" },
    meta: "Sep 2025",
    tag: "Chat with creator personas",
    category: "AI chat app",
    problem: "Generic assistants all sound the same.",
    built: "Chat that takes on a creator's tone and style, with streaming replies in many languages.",
    result: { value: "Streaming", unit: "Multilingual persona chat" },
    stack: ["OpenAI SDK", "Gemini", "Next.js"],
    live: "https://ai-persona-chat-yhp9.vercel.app",
    repo: gh("AI-Persona-Chat-App"),
  },
];
